### ISSUE TITLE
iOS device reports 'Printer is Offline'

### ISSUE THREAD

**Issue by rdlugosz** [tjfontaine/airprint-generate#10]
On a default Ubuntu 12.04 LTS install I used the airprint-generate script and followed the steps mentioned in issue #5 to add the mime types. The printer appeared to my iOS devices but when you attempted to print iOS would report "The printer is offline".

The fix is that you have to make sure the CUPS server is publishing it's printers. I suspect what happens is that Avahi publishes the name of the printer but since CUPS isn't set to make that printer available to network users the printer appears to be offline when iOS attempts to use it. 

Look for the setting "Share published printers connected to this system" in the CUPS server prefs menu.

I am going to immediately close this issue; just leaving it here for the benefit of others.

**Comment by antmak** [comment]
```
Listen *:631
```
is very helpful! @tjfontaine Could you add mdns and cups port numbers into README, to be consistent in firewall setup?
