### ISSUE TITLE
Errors with python3

### ISSUE THREAD

**Issue by AlexMorro** [tjfontaine/airprint-generate#23]
I know it's not an issue for me but for others it can be, I changed the imports and now works with python3.
https://pastebin.com/gMB8pPCg

If you are allowed to push files feel free to push my file.

**Comment by rchenzheng** [comment]
> I know it's not an issue for me but for others it can be, I changed the imports and now works with python3.
> https://pastebin.com/gMB8pPCg
> 
> If you are allowed to push files feel free to push my file.

Why don’t you make a pull request ?

**Comment by rchenzheng** [comment]
I've managed to refactor the code and get it working as well as adding docker support, thanks for the inspiration @AlexMorro

**Comment by tjfontaine** [comment]
fixed in 0384693e462ee6a0bf9237a839d73d4c6a720cd3
